package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.SharedResources
import jetbrains.buildServer.configs.kotlin.v2018_1.sharedResources
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    features {
        val feature1 = find<SharedResources> {
            sharedResources {
                lockSpecificValue("Resource_with_values", "value1")
            }
        }
        feature1.apply {
            readLock("Resource_with_values")
        }
    }
}
