package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildFeature
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    features {
        val feature1 = find<BuildFeature> {
            feature {
                type = "JetBrains.SharedResources"
                param("locks-param", "Resource_with_values readLock value1")
            }
        }
        feature1.apply {
            param("locks-param", "Resource_with_values readLock")
        }
    }
}
