package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.SharedResource
import jetbrains.buildServer.configs.kotlin.v2018_1.sharedResource
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<SharedResource> {
            sharedResource {
                id = "PROJECT_EXT_62"
                name = "Resource_with_values"
                resourceType = customValues(
                    "value1",
                    "value2",
                    "value3"
                )
            }
        }
        feature1.apply {
            name = "Resource_with_values"
            resourceType = customValues(
                "value1",
                "value2",
                "value3"
            )
        }
    }
}
